### ISSUE TITLE
adding lets encrypt SSL to ghost blog

### ISSUE THREAD

**Issue by jasan-s** [cobyism/ghost-on-heroku#101]
this is a question rather than an issue, but I can't seem to figure out how to provision a lets encrypt SSL cert with this deployed blog on Heroku.

**Comment by WaqasIbrahim** [comment]
Follow this to generate a crt file and you can upload it. 
https://gethttpsforfree.com/

But you will need to upgrade to a paid dyno to use SSL.

**Comment by jasan-s** [comment]
@WaqasIbrahim thanks i actually tried that earlier , got as far as step 4 I assumed it would require DND TXT records or something for verification but it instead wanted me to run a local server or something. And I believe Heroku offers SSL starting with $7 hobby plan so if i upgrade i wouldn't need my own.

**Comment by WaqasIbrahim** [comment]
You can use the alternate method and verify by serving a file. And even if you want to use your own SSL, you will need to upgrade. SSL is not available for free dynos.

**Comment by byt3smith** [comment]
Yes, you have to upgrade to Hobby dynos to use SSL. 

Once you upgrade to a Hobby dyno, you can serve up the Let's Encrypt verification by adding a separate dyno and using a separate server, like a Python or NodeJS server, to serve the required route.

**Comment by freekrai** [comment]
I use https://github.com/dmathieu/sabayon to handle the provisioning and renewals, and then I also run ghost as middleware with the route handled by express.

There are a lot of ways around the actual provisioning process, including adding a file itself, but since the certs expire every 90 days, you want to be able to have them auto-renew.

I have Sabayon running for four different Heroku sites right now, and yes as @byt3smith mentioned, you have to upgrade to Hobby to add an SSL cert to your site.

The $7 dollar hobby plan does not include an actual SSL cert, it gives you SSL cert access, so you'd still have to add your own cert.

**Comment by jmonster** [comment]
PSA: SSL is free on Heroku now thanks to SNI and Let's Encrypt: https://blog.heroku.com/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours

**Comment by mars** [comment]
As @byt3smith commented, [Heroku ACM](https://devcenter.heroku.com/articles/automated-certificate-management) solves this problem by automating free SSL for custom domains with any paid dyno.
