### ISSUE TITLE
[documentation request] about setting up Mailgun

### ISSUE THREAD

**Issue by KageKirin** [cobyism/ghost-on-heroku#121]
Hello,

I've been running my blog successfully on Heroku for 2 years thanks to your great work.
Recently, I've managed to lock myself out due to _NOT_ having configured Mailgun correctly to start with, resulting in recovery emails not being sent.
Long story short, my Mailgun account is now verified, and I'm trying to setup the remaining variables to get my domain verified.

> 2. Add DNS Records For Sending
> TXT records (known as SPF & DKIM) are required to send and receive email with Mailgun.

> 3. Add DNS Records For Tracking
> The CNAME record is necessary for tracking opens, clicks, and unsubscribes.

As I'm just using myapp.herokuapp.com as DNS, I'm lost as to where I should set up those variables.
Any help or pointers to documentation would be welcome.

Best regards,
KageKirin

(currently dead blog at http://kagekirinblog.herokuapp.com)

**Comment by cobyism** [comment]
Sorry to hear you ran into trouble with this. I’m not actually sure what the answer is, given that you’re using a Heroku subdomain rather than one you control, but Heroku or Mailgun’s support teams should be able to shed some light on the situation.

I’m going to close this issue here though, as it’s not really related to this codebase. Hope you find a solution! 🙂
