### ISSUE TITLE
Run on /blog

### ISSUE THREAD

**Issue by acrogenesis** [cobyism/ghost-on-heroku#123]
Do you think it's possible to run this on domain.com/blog and have a static page on domain.com?

**Comment by wi-ski** [comment]
Reverse proxy. https://github.com/heroku/heroku-buildpack-static

**Comment by cobyism** [comment]
Heroku essentially expects that every app will live at a domain or subdomain level. Perhaps something like [fly.io might help you achieve what you need](https://fly.io/articles/delivering-multiple-applications-on-one-hostname/)?

I’m going to close this, since it’s not really within the responsibility of this codebase.
