### ISSUE TITLE
Application is asking for my payment information

### ISSUE THREAD

**Issue by hkalant** [cobyism/ghost-on-heroku#14]
Hey there,

After I clicked the purple "Deploy on Heroku" button, I set the app name etc and when I click the "Deploy for free" button, while it is configuring environment, it asks me to fill my payment information to verify my identity. Is it necessary to do that? is it gonna charge me?

Thanks,
Harry

**Comment by cobyism** [comment]
That's odd. Nothing about this application requires payment, and all the addons specified are the free version. Perhaps Heroku require a card on file in case you decide later to add dynos or other paid resources? In any case, I'd recommend contacting Heroku support to clarify. I'm going to close this issue, because I'm confident it's nothing to do with this application, but if you find out something to the contrary please reopen so we can fix it.

**Comment by ili-codes** [comment]
Had the same issue here. Will contact support.

**Comment by johnbeynon** [comment]
We require accounts to be verified to use 3rd party addons. You could use Heroku Postgres without verifying but MailGun (even the free version) requires you to verify your account - there's no charge here, it's just to verify your identity. See https://devcenter.heroku.com/articles/account-verification for more details.

**Comment by holic** [comment]
Thanks for the answer @johnbeynon!
