### ISSUE TITLE
Images added to S3 but not completing upload

### ISSUE THREAD

**Issue by jkentjnr** [cobyism/ghost-on-heroku#18]
Getting an issue when I upload a blog cover or logo where the image is uploaded to Amazon S3 but the UI never completes.  It simply displays the wiggly cat indefinitely. Is there anyway to view the logs for ghost-on-heroku or does this issue sound familiar? 

Cheers,
James

**Comment by cobyism** [comment]
Sounds like you haven’t got the S3 bucket policy configured to allow read-access for anonymous clients. If that’s the case, then you’ll want to head to your AWS console, find the bucket in S3, and make sure you have an appropriate policy set up.

![2015-05-25 at 9 43 am](https://cloud.githubusercontent.com/assets/296432/7794502/1658281c-02c3-11e5-820c-bf2f85ac6c37.png)

Then put a policy in place along these lines:

![2015-05-25 at 9 48 am](https://cloud.githubusercontent.com/assets/296432/7794515/4746ffca-02c3-11e5-9664-72ccb3e86022.png)

E.g. if your bucket name is `mybucket`, then the policy might look like:

```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "MakeEverythingPublic",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::mybucket/*"
		}
	]
}
```

Feel free to reopen if this turns out to be something different :+1:

**Comment by farschmessivo** [comment]
Hi @cobyism I'm still having issues after tweaking the bucket policy 

![screenshot 2015-06-15 14 08 52](https://cloud.githubusercontent.com/assets/331717/8160523/4a70d936-1368-11e5-9934-9a1d8ee0d2c7.png)

**Comment by cobyism** [comment]
@farschmessivo Is this the same issue as you’ve opened in #20? or are you seeing that error when public users attempt to read images stored in S3?

**Comment by jonathanconway** [comment]
Having this issue still, even after adding a policy as suggested above. @farschmessivo did you manage to fix this?

**Comment by jonathanconway** [comment]
Never mind, fixed it by fixing the region to be correct. 👍
