### ISSUE TITLE
upgrade to 0.5.10

### ISSUE THREAD

**Issue by tkisme** [cobyism/ghost-on-heroku#7]
please upgrade ,thanks

**Comment by cobyism** [comment]
@tkisme If you have some spare cycles feel free to run the steps @awendt detailed in https://github.com/cobyism/ghost-on-heroku/pull/4 and send a pull request to update this repository and I’ll merge it, otherwise I’ll get to it eventually but I can’t guarantee how long (travelling for the next week or so).

**Comment by cobyism** [comment]
Closed by #8.
