### ISSUE TITLE
Newly created app not a git repo

### ISSUE THREAD

**Issue by ratulotron** [cobyism/ghost-on-heroku#84]
After creating and testing the live app, I cloned the source to my workstation with `heroku git:clone appname`. In return I get an empty repo. Then I tried to ssh to the app and create a git repo manually. The ssh terminal simply freezed, and the app crashed.

**Comment by holic** [comment]
Can you try the instructions here? https://github.com/cobyism/ghost-on-heroku#updating

**Comment by ratulotron** [comment]
When I logged in with ssh, all the files were there from cobyism/ghost-on-heroku. It was just that this one wasn't a git repo at all. The ssh was freezing because of my bad internet connection, I was able to initialize /app folder as a git repo later. I deleted and recreated the app from this repo a bunch of times to understand what was happening. At the end I did these to solve the problem last night: 

1. Cloned the empty folder by `heroku git:clone -a APPNAME`
2. SSH to heroku and initialized `/app` folder as a git repo
2. Took a back up of that copy in my github account: https://github.com/ratulotron/ghost-blog
3. Added my backup as the remote for origin:master in the cloned empty folder
4. Pulled from backup and added a custom theme and committed
5.  Finally pushed to heroku:master, just to see if it works

I just had too much time in my hands :smiley_cat: And it worked. As of now my customization is still there. Git pull and push works on heroku:master. But the interesting thing is, after a day I see that the `/app` is now a plain folder, even though I did all the git operations in it last night:
```
~ $ ls
LICENSE   README.md  config.js	node_modules  server.js
Procfile  app.json   content	package.json
~ $ git status
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
~ $ pwd
/app
~ $ 
```

**Comment by cobyism** [comment]
> Newly created app not a git repo

> …

> the interesting thing is, after a day I see that the /app is now a plain folder, even though I did all the git operations in it last night…

Thanks for opening an issue @ratulotron, however I think you might be misunderstanding [how the Heroku deployment process works](https://devcenter.heroku.com/articles/how-heroku-works#building-applications). On Heroku, all interactions and deployments happen via Git, but the actual compiled slug with your application’s files on it (and the resulting dyno that gets run) after you `git push` isn’t a git remote at all.

In the same way that the Heroku filesystem [isn’t where you should persist data](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem), Heroku deployments aren’t like a regular VPS where your app gets a single server instance spun up and which gets updated when you push—instead, when you `git push`, Heroku will build and compile the necessary [slug](https://devcenter.heroku.com/articles/slug-compiler), and spin up one (or more) dynos using that slug as a template.

That’s why if you SSH into the dyno with `heroku run bash --app APPNAME`, you won’t find a `.git` directory anywhere—and that’s to be expected. It’s also worth noting that you also aren’t even really SSHing "into" your app’s dyno per-se either, given that `heroku run` actually creates a dedicated [one-off dyno](https://devcenter.heroku.com/articles/one-off-dynos) in which commands are run instead.

Hopefully this helps give you a better idea of why you’re seeing what you’re seeing 😃. I’m going to go ahead and close this because I don’t believe this represents an issue with this project, however don’t let that stop you asking questions below. 👍

**Comment by ratulotron** [comment]
I got a little sidetracked while describing the issue. I came to know about the Heroku's filesystem not intended for holding static files while deploying a Flask app earlier this year. Uploading a contact list was a requirement for that project. Soon I realized the app doesn't keep the uploaded files unless it was added to the git from my source. Thanks for explaining the thing about dyno, now I get it how Heroku simply provides a throw-away version of the app when I want to run commands remotely.

Now about the original problem, it still is there. I created a new app(https://ratul-ghost.herokuapp.com/) just to demonstrate that "heroku git:clone" gives an empty repo.

    % heroku git:clone --app ratul-ghost                                ~ perhonen
    Cloning into 'ratul-ghost'...
    warning: You appear to have cloned an empty repository.
    Checking connectivity... done.
    % cd ratul-ghost                                                    ~ perhonen
    % ls                                           ~/ratul-ghost (master) perhonen
    %

As per readme for this repo, to add a theme I can do the following.

> 
> To make changes to your Ghost blog (like adding a theme to the /content directory, for instance), clone your blog locally using the Heroku Toolbelt:
> 
>     heroku git:clone --app YOURAPPNAME
> 
> 

Obviously this won't work if the cloned folder is empty. @holic 's suggestion works, just as the convoluted workaround I found works. Which means the instruction in this doc needs to be changed.

**Comment by cobyism** [comment]
> the original problem, it still is there. I created a new app(https://ratul-ghost.herokuapp.com/) just to demonstrate that "heroku git:clone" gives an empty repo.

@ratulotron Yes. Unfortunately, this [appears to be a known problem](https://kb.heroku.com/why-do-i-see-a-message-you-appear-to-have-cloned-an-empty-repository) on Heroku’s end with apps that have been deployed via their platform API, and it’s something that a few people have run into before when deploying Ghost using this project—see https://github.com/cobyism/ghost-on-heroku/issues/67 and https://github.com/cobyism/ghost-on-heroku/issues/62. Until something changes on Heroku’s end, there’s not much we can do. 😣 

If there are specific changes to the README you’d suggest as a result of this issue, it’d be great to get a PR open so we can start a discussion 😀

**Comment by ratulotron** [comment]
Oh I see, I stupidly assumed it must be something with this repo that's wrong, rather that in Heroku. I think this problem can be added to the README as a note, then at least users would know something like this might happen.
