### ISSUE TITLE
External File Systems

### ISSUE THREAD

**Issue by StewartJarod** [cobyism/ghost-on-heroku#9]
https://github.com/TryGhost/Ghost/issues/4600 has been closed. 

:rocket:

**Comment by cobyism** [comment]
Yeah, I stumbled across that the other day, which is why I added the note about it to the readme. It didn’t look like it was finalized as a feature though, despite that specific issue being closed. Has external file storage landed in a formal release yet in a way that we can take advantage of using Ghost as an NPM module like we are here?

**Comment by StewartJarod** [comment]
hrmm, I think you are right. The issue was closed and merged to master but that has not yet been merged in stable.

My bad!

**Comment by cobyism** [comment]
No worries! I appreciate you opening the issue. If you see or hear anything about this being included in an official release before I do, let me know! :+1:

**Comment by tswicegood** [comment]
FWIW, it looks like updates will be posted to https://github.com/TryGhost/Ghost/pull/4820 once they're ready / released.

**Comment by cobyism** [comment]
@tswicegood Thanks, I’ll keep an eye out :+1:

**Comment by cobyism** [comment]
Looks like https://github.com/TryGhost/Ghost/pull/4820 is all wrapped up, and the new documentation is available at https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module. Anyone want to take a crack at adding (optional) support for s3 storage to this repo?
