### ISSUE TITLE
Ghost v1.0 will not support config.js anymore.

### ISSUE THREAD

**Issue by legendtang** [cobyism/ghost-on-heroku#90]
Check https://github.com/TryGhost/Ghost/commits/master/config.example.js for detail.

That means we cannot run `node server.js` to load `config.js` just like before?

**Comment by diervo** [comment]
After reading the issue and the code, their move to use `nconf` has made any heroku integration much more tricky since nconf expects preexisting json files, and they merge the config as the server gets initialized (can't monkey patch after).

I guess didn't think too much on this pattern and its consequences with integrations?

Given that for heroku we need dynamic variables (such as the PORT) the only viable option would be  to override the configuration file before invoking the server initialization.

I will try to give it a run when I have time.

**Comment by diervo** [comment]
Here is a trivial example in how to override the config:

```
var ghost = require('ghost');

ghost().then(function (ghostServer) {
    var config = require('./node_modules/ghost/core/server/config');
    config.set('server:port', process.env.PORT);
    console.log(config);
    ghostServer.start();
});
```
We can probably remove the hardcoded path using require.resolve().

My 2cents.

**Comment by diervo** [comment]
@cobyism FYI, hopefully one less blocker :)

**Comment by mars** [comment]
See PR for Ghost 1.x: https://github.com/cobyism/ghost-on-heroku/pull/119

In that branch the new `config.production.json` file is generated through a [`.profile` script](https://github.com/cobyism/ghost-on-heroku/pull/119/files#diff-593308ff3a1800e7975e8fdd7f830dd3) that builds upon the previous `config.js` logic.

It's also possible to [directly use environment variables](https://docs.ghost.org/v1.0.0/docs/config#section-running-ghost-with-config-env-variables) with a few limitations. These may be set a config vars:

```bash
heroku config:set privacy__useUpdateCheck=false
```

**Comment by cobyism** [comment]
#119 has been merged in, so I’m going to close this out.
